### ISSUE TITLE
Warnings with webpack

### ISSUE THREAD

**Issue by gdub22** [graphql/graphql-language-service#111]
When this package is bundled with webpack, warnings are emitted ("Critical dependency: the request of a dependency is an expression") because of the dynamic requires here: 

https://github.com/graphql/graphql-language-service/blob/580d2242fb68c90c61a01a04f46629cb0c5fdd7a/packages/graphql-language-service-interface/src/GraphQLLanguageService.js#L81-L83

I encountered this when upgrading graphiql to 0.10.2, which depends on codemirror-graphql, which depends on this.

**Comment by asiandrummer** [comment]
@gdub22 Thanks for reporting ;) https://github.com/webpack/webpack/issues/196 seems to be tracking this issue

**Comment by danez** [comment]
The problem is also, that the dynamic require makes webpack pickup all files including *.flow files which cannot be parsed.

**Comment by asiandrummer** [comment]
@danez I see - thanks for the explanation. To clarify I didn't mean to blame Webpack for this issue - just wanted to mention some alternatives we could try out from that issue. Apologies for confusion.

"require context" sounds like a good alternative to me, with some module name parsing since the module path would come from `.graphqlconfig` file.
```
const customValidationRules = require('./dir/' + somePath + '.js');
```

**Comment by danez** [comment]
@asiandrummer Yes that should probably make webpack not complain and only include valid files.

Thanks for looking into this.

**Comment by tsunammis** [comment]
@asiandrummer @danez @gdub22 Do you have an idea to make that thing working ?

**Comment by asiandrummer** [comment]
@tsunammis I meant to look into this issue, but had been sidetracked to work on other things meanwhile. I promise I'll deal with this and release a new patch version by this week. Sorry for the delay.

**Comment by tsunammis** [comment]
@asiandrummer Thanks ;-)

**Comment by danez** [comment]
As a workaround o can exclude flow files from being process by webpack, by adding this plugin:

```js
// Only consider js files for the context
new webpack.ContextReplacementPlugin(/graphql-language-service-interface[\/\\]dist/, /\.js$/),
```

The warning will still be there, but at least it works.

**Comment by asiandrummer** [comment]
Finally came around this! I'll cut a new release soon, and update `codemirror-graphql` and `graphiql` accordingly as well.

**Comment by zdne** [comment]
@asiandrummer has this been addressed & published yet?

**Comment by gdub22** [comment]
@asiandrummer thanks for the fix. `codemirror-graphql` has this dep locked so I'm unable to get the update in the latest graphiql release

https://github.com/graphql/codemirror-graphql/blob/713c092c1ddf4427e134b132e2611d0cbcb15c8e/package.json#L50

**Comment by jlsphar** [comment]
@asiandrummer thanks for the fix! Can you cut a release to publish? Many thanks!

**Comment by wincent** [comment]
I'm going to cut a codemirror-graphql release shortly and will make sure the deps are up-to-date before I do.

**Comment by gdub22** [comment]
@wincent thanks for releasing.  Unfortunately, this dependency is still locked on the old version in the latest codemirror-graphql 0.6.8 just released.

https://github.com/graphql/codemirror-graphql/blob/28366f8939bb6f2551b938991134e5591c653490/package.json#L52

**Comment by wincent** [comment]
Ah, thanks for pointing it out @gdub22. I can cut another release later today.

**Comment by wincent** [comment]
@gdub22: I just cut v0.6.9 (https://github.com/graphql/codemirror-graphql/releases/tag/v0.6.9) — let me know if that doesn't resolve things for you.

**Comment by ddgromit** [comment]
I'm not sure why but codemirror-graphql is still resolving to `graphql-language-service-interface@0.0.16`.  Tested with fresh packages in both yarn and NPM:

```
➜   yarn add codemirror-graphql
yarn add v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "codemirror-graphql@0.6.9" has unmet peer dependency "codemirror@^5.26.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 8 new dependencies.
├─ codemirror-graphql@0.6.9
├─ graphql-language-service-config@0.0.15
├─ graphql-language-service-interface@0.0.16
├─ graphql-language-service-parser@0.0.14
├─ graphql-language-service-types@0.0.20
├─ graphql-language-service-utils@0.0.15
├─ graphql@0.10.3
└─ iterall@1.1.1
✨  Done in 1.14s.
```

**Comment by gdub22** [comment]
@wincent I'm getting the same issue/output as @ddgromit

**Comment by cberkom** [comment]
Same here. Looks like `codemirror-graphql@0.6.9` [still depends](https://github.com/graphql/codemirror-graphql/blob/de27700df1fbac49b3e1dae51fe834436802b4e5/package.json#L52) on `graphql-language-service-interface@^0.0.16`. (Thanks, @wincent)

@gdub22 @ddgromit is there a workaround while we wait?

**Comment by ddgromit** [comment]
Ah the problem is you'd think `^0.0.16 := >=0.0.16 <0.1.0` but it really means `^0.0.3 := >=0.0.3 <0.0.4` since the first leading non-zero number is the patch level version.  So, in this particular case the caret is meaningless.

@wincent I think this can be fixed by one of:
- changing the `graphql-language-service-interface` version to `>=0.0.16 <0.1.0`
- OR bumping the minor versions of all the packages in the next release to `0.1.0` and making the dependencies reference `^0.1.0`

The dependency could be set to to `graphql-language-service-interface@^0.0.18` like @cberkom suggested which would fix the graphql bug, but wouldn't "loosen" the dependency for the future.  `0.0.18` would be the only valid version.

**Comment by asiandrummer** [comment]
@ddgromit thanks for the analysis. I'm sorry for the trouble this has caused over time - I'll test out the `>=0.0.16 < 0.1.0` fix for now. I'll probably be able to do a minor version release soon as well.

**Comment by asiandrummer** [comment]
@ddgromit @cberkom @gdub22 
`yarn add codemirror-graphql` gives me 
```
Using globally installed version of Yarn
yarn add v0.24.3
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "codemirror-graphql@0.6.10" has unmet peer dependency "codemirror@^5.26.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 6 new dependencies.
├─ codemirror-graphql@0.6.10
├─ graphql-language-service-config@0.0.17
├─ graphql-language-service-interface@0.0.19
├─ graphql-language-service-parser@0.0.15
├─ graphql-language-service-types@0.0.21
└─ graphql-language-service-utils@0.0.17
warning No license field
✨  Done in 2.40s.
```

Could one of you verify `0.6.10` release fixes your issue please?

**Comment by gdub22** [comment]
It's pulling the latest version now.  There are a bunch of new warnings with .flow files now.  Original warning I reported is gone.

**Comment by asiandrummer** [comment]
@gdub22 I'm getting several as well - some of them don't sound right, as they're showing error for not being able to find installed modules such as `graphql` and `codemirror`. I'm looking into it

**Comment by gdub22** [comment]
I can just explicitly ignore `.flow` files in my own webpack config and the warnings are gone and all is well.  I'm not sure where or why they are even being attempted to be imported now though.

**Comment by stubailo** [comment]
Ouch. I hope this doesn't break stuff for people using Browserify as well, since Webpack isn't the only module bundler out there.
