### ISSUE TITLE
Flow checks are busted in Travis CI

### ISSUE THREAD

**Issue by wincent** [graphql/graphql-language-service#139]
Sample failure: https://travis-ci.org/graphql/graphql-language-service/builds/265282225

Repros locally too with a `yarn run check` (28 errors).

cc @asiandrummer for visibility

**Comment by danez** [comment]
This is now failing because of this: https://github.com/graphql/graphql-js/issues/1045

**Comment by asiandrummer** [comment]
I just resolved graphql/graphql-js#1045 - I'll release a patch and will update this library to reflect the changes.
