### ISSUE TITLE
Consider removing multi-app support in configs

### ISSUE THREAD

**Issue by nodkz** [graphql/graphql-language-service#15]
According to [`.graphqlrc` redesign proposal](https://github.com/graphcool/graphql-config/issues/16) and my strongly feeling that multi-app is evil in this config file - I ask you to consider removing multi-app from `graphql-language-service`. Let try to implement your monorepo needs in some other way.

#### 1. Problem with `getConfigByFilePath`, it may returns wrong config
Inspecting `graphql-language-service` I found that [this code](https://github.com/graphql/graphql-language-service/blob/e38c2ffa22d1c1588defcbb59fbb873c1966ed91/src/config/GraphQLConfig.js#L110-L117) that may bring problems:
```js
  getConfigByFilePath(filePath: Uri): ?GraphQLConfig {
    const name = this.getConfigNames().find(configName =>
      this.getConfig(configName).isFileInInputDirs(filePath),
    );
    return name ? this._configs[name] : null;
  }
```
It determines by filePath in input dirs app specific config and return it. So the problem may be if several apps will have the same file in `input-dirs`. You will get first config, but in reality may be needed another config.

#### 2. CLI interface missing option
CLI may be pointed to `multiapp` config, so it should be somehow informed which config needs to take. In this case needed an additional option which will point to needed app name. 

On the other hand, adding this option we complicate integration with IDE (it can not automatically choose the correct app, will need to provide some dialog window where a user chooses needed app). So as joke solution we may add one more dot-rc file.

---

So if we make restriction, that `.graphqlrc` contains only one app, all above problems disappears. Of course need to solve your monorepo problem. If you provide some real case, maybe we can find another solution together?

**Comment by asiandrummer** [comment]
@nodkz thanks for finding that issue! These are certainly valid cases and I do agree that pushing for a generalized approach for dealing with monolithic repositories is a bit early/premature at this point. I will continue this discussion in `graphql-config` repository - for this library we should indeed start from the single-app use case. I'll follow up with a PR shortly.

**Comment by asiandrummer** [comment]
Ah forgot to mention why the above logic exists - I've put in a hard assumption that all `inputDirs` and `excludeDirs` are mutually exclusive - that is, each app contains a distinct set of directory paths to each other, and this notion directly contradicts the first case. This is of course a bad assumption to make in a long term, but was implemented in place at the time to facilitate the development.

**Comment by nodkz** [comment]
> `inputDirs` and `excludeDirs` are mutually exclusive
Got this.
@asiandrummer thanks for your explanation. So, in this case, my issue is no more valid.
