### ISSUE TITLE
Use language server protocol watch instead of watchman when available

### ISSUE THREAD

**Issue by stephen** [graphql/graphql-language-service#206]
It seems nice to support using language server protocol [file watch events](https://microsoft.github.io/language-server-protocol/specification#didchangewatchedfiles-notification-arrow_right) over watchman when it's available.

This would mean that extensions wishing to use the service would not have to additionally install `watchman` through some other delivery channel.

**Comment by mgadda** [comment]
I've started working on a patch for this. My approach here will be not to remove the watchman dependency but rather to respect the client capabilities passed "up" from the client. If they include `didChangeWatchedFiles`, then the language server will rely on the client for file watch events. If they do not include `didChangeWatchedFiles`, watchman will be used as it is today.

I'll post a link to my forked branch soon for anyone interested later this week.

**Comment by stephen** [comment]
Exciting. I am very interested! Your approach also sounds nice to me to keep compatibility with existing clients that opt for watchman instead.

**Comment by mgadda** [comment]
Closing now that https://github.com/graphql/graphql-language-service/pull/218 has been merged.
