### ISSUE TITLE
Incompatible graphql-language-service-utils

### ISSUE THREAD

**Issue by brosander** [graphql/graphql-language-service#239]
In npm, the current version of graphql-language-service-utils is 1.2.1 which seems to have issues when resolved transitively by the other older components.

Forcing graphql-language-service-utils to 1.2.0 resolves our build issue.

**Comment by JWimsingues** [comment]
Same experience on our side...
Getting this error message
```
Module not found: Error: Can't resolve 'graphql/validation/rules/ExecutableDefinitions' in '../node_modules/graphql-language-service-utils/dist'
```
solved by forcing by reverting to the last release which worked on our side (graphql-language-service-utils-1.0.18.tgz")

**Comment by jlai** [comment]
ExecutableDefinitions.js doesn't exist until graphql 1.12.0, but https://github.com/graphql/graphql-language-service/blob/master/packages/utils/package.json allows 0.10.0 and up

**Comment by lostplan** [comment]
So, as far as I can tell, either we need to revert https://github.com/graphql/graphql-language-service/commit/068c57fdb4a147be3c2fc38167e2def74d217a82 or utils needs to drop peerdep support for graphql v0.10 and v0.11. Does that sound right?

Pinging authors @divyenduz @asiandrummer – do you have any thoughts on this? Is there any precedent for when/how to drop support for older peerdeps?

**Comment by tgvashworth** [comment]
Hey folks — I ran into this again today. Any progress?

**Comment by lostplan** [comment]
v0.12 was released back in December so let's drop support for v0.11 (and below). This will require a major version bump for graphql-language-service.

Could someone make a PR?
