### ISSUE TITLE
GraphQL Language Service IntelliJ plugin

### ISSUE THREAD

**Issue by asiandrummer** [graphql/graphql-language-service#4]
Hi @jimkyndemeyer and @martijnwalraven - I've been talking to you guys individually, but you guys have experiences/working examples of the IntelliJ plugin for GraphQL Language Service, which is amazing btw :D I just wanted to initiate the discussion for us to collaborate together in creating a IntelliJ plugin using this GraphQL Language Service and the server!

For the actual details to making it happen I have less preferences - I thought that we could either work together on already-existing @jimkyndemeyer's IntelliJ plugin and improve that, or start from the scratch depending on how the plugin development is structured and etc. You guys obviously have a better idea how this goes, but I'm here to help as much as I can.

Also, note that by us working together to implement this, we can make any changes we want in this graphql-language-service repo to fit your needs when this is still a private repo. Let me know how we can proceed!

**Comment by mickaelistria** [comment]
> I also still think we may want to take a look at Visual Studio Code's new language service protocol to see if it makes sense to build on that.

Definitely! Supporting this protocol allows good integration in [multiple IDEs](https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations#editors-ides-supporting-the-protocol) with very minimal effort.

**Comment by darrinps** [comment]
Don't know if I'll be able to add much with respect to coding (although I could try if needed), I'd like to be able to try the tool and provide feedback if that would be beneficial in helping this along.

**Comment by wincent** [comment]
> Supporting this protocol allows good integration in [multiple IDEs](https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations#editors-ides-supporting-the-protocol) with very minimal effort.

Yeah, @asiandrummer already took a stab at implementing this in the service (see [here](https://github.com/graphql/graphql-language-service/commit/820b03c52c245e3ca09ba3739ed159240328927c) and other commits on `master`).

**Comment by asiandrummer** [comment]
@darrinps that would be fantastic! This is still in a technical preview (and does need a lot of improvements before we get out of it), so please feel free to try out and give unsolicited feedback!

**Comment by asiandrummer** [comment]
Opened https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/62 to keep this conversation going :D
